apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: service-hubble
  name: service-hubble-config
  namespace: sealos
data:
  config.yml: |
    http:
      addr: ":8080"
    hubble:
      addr: "hubble-relay.kube-system.svc.cluster.local:80"
    redis:
      addr: 
      password: 
      db: 0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-hubble
  name: service-hubble-deployment
  namespace: sealos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-hubble
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service-hubble
    spec:
      containers:
        - args:
            - --config=/config/config.yml
          command:
            - /manager
          image: bearslyricattack/sealos-hubble-service:latest
          imagePullPolicy: Always
          name: service-hubble
          ports:
            - containerPort: 8428
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 640Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              name: config-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: service-hubble-config
          name: config-vol
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-hubble
  name: service-hubble
  namespace: sealos
spec:
  ports:
    - name: http
      port: 8428
      protocol: TCP
      targetPort: 8428
  selector:
    app: service-hubble
